implementazioen admin modifica i dati dell'utente
gaetanoAlessandrettolavoro/Activity-Tracker-FE pull request #145
Opened 2024-06-21 11:53 UTC by erikacimi

PatchUser

2024-06-21 12:26 UTC, gianmarco2307 requested changes
Not good; we're using angular with components, you have replaced all with an html file, with script inside

2024-06-21 12:30 UTC, RitaCaterina approved these changes

2024-06-21 12:30 UTC, CalogeroRaia approved these changes

2024-06-21 14:45 UTC, CalogeroRaia approved these changes

2024-06-26 13:35 UTC, CalogeroRaia approved these changes

2024-06-26 13:36 UTC, closed without merging